spring:
  application:
    name: quanlygiaidaubongdaBE
  datasource:
    url: jdbc:mysql://localhost:3306/quanlygiaidaubongda?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: datn20232024
  cache:
    type: redis
    redis:
      time-to-live: 3600
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
#Cloud
CLOUDINARY_CLOUD_NAME: ${CLOUD_NAME}
CLOUDINARY_API_KEY: ${API_KEY}
CLOUDINARY_API_SECRET: ${API_SECRET}

